import Image from 'next/image'
import { Workspace } from '@/components/platform/workspace'
import { ArrowUpRight, Bot, ChartNoAxesCombined, Fingerprint, Globe2, Layers3, Megaphone, Search, Sparkles, Workflow } from 'lucide-react'

const services = [
  { icon: Fingerprint, title: 'Brands worth remembering.', tag: 'BRAND & CREATIVE', text: 'Positioning, visual identity, and compelling creative built around what makes your business different.' },
  { icon: Globe2, title: 'Experiences that convert.', tag: 'WEB & CONVERSION', text: 'Websites, landing pages, and conversion journeys that connect a first impression to a meaningful next step.' },
  { icon: Search, title: 'Get found. Stay relevant.', tag: 'SEO & CONTENT', text: 'Search strategy and audience-first content designed to make your expertise easier to discover.' },
  { icon: Megaphone, title: 'Campaigns with direction.', tag: 'PAID & SOCIAL', text: 'Campaign planning, creative direction, and social strategy that work toward the same business goals.' },
  { icon: Workflow, title: 'Less busywork. More momentum.', tag: 'AUTOMATION & SYSTEMS', text: 'Map your lead journey, identify bottlenecks, and design connected workflows for your team.' },
  { icon: Bot, title: 'Intelligence with context.', tag: 'AI & KNOWLEDGE', text: 'Work with Ava Skye on strategy grounded in your private brand documents, not a generic blank prompt.' },
]

export default function Home() {
  const checkout = process.env.PAYPAL_CHECKOUT_URL
  const safeCheckout = checkout && /^https:\/\/(www\.)?(paypal\.com|paypal\.me)\//.test(checkout) ? checkout : null
  const video = process.env.AVA_WALKTHROUGH_VIDEO_URL
  const safeVideo = video?.startsWith('https://') ? video : null
  return <main id="top">
    <a className="skip-link" href="#workspace">Skip to workspace</a>
    <nav className="nav" aria-label="Main navigation"><a href="#top" className="brand-logo" aria-label="DigiMark101 home"><Image src="/digimark101-logo.svg" alt="DigiMark101 — Ideas into impact" width={720} height={300} priority unoptimized /></a><div><a href="#services">Our expertise</a><a href="#experience">The approach</a><a className="nav-cta" href="#workspace">Enter workspace <ArrowUpRight size={15} /></a></div></nav>
    <section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="dot" /> THE NEXT ERA OF DIGITAL GROWTH</div><h1>Think bigger.<br />Build smarter.<br /><em>Grow beyond.</em></h1><p>A digital marketing agency with intelligence built in. Brand, web, campaigns, and AI strategy—one connected vision for your next chapter.</p><div className="actions"><a className="primary" href="#services">Discover your next advantage <ArrowUpRight size={17} /></a><a className="secondary" href="#workspace">Meet Ava Skye <Sparkles size={16} /></a></div><div className="hero-meta">HUMAN CREATIVITY. CONNECTED SYSTEMS. AI POSSIBILITY.</div></div>
    <div className="growth-art" aria-label="Illustration of the DigiMark101 connected growth approach"><div className="art-topline"><span><span className="dot" /> THE GROWTH ECOSYSTEM</span><Layers3 size={20} /></div><div className="ecosystem"><div className="ecosystem-ring ring-outer" /><div className="ecosystem-ring ring-inner" /><div className="intelligence-core"><Sparkles size={30} /><strong>AVA</strong><span>SKYE INTELLIGENCE</span></div><div className="system-node node-brand"><Fingerprint size={20} /><span>Brand</span></div><div className="system-node node-web"><Globe2 size={20} /><span>Web</span></div><div className="system-node node-campaign"><Megaphone size={20} /><span>Campaigns</span></div><div className="system-node node-systems"><Workflow size={20} /><span>Systems</span></div></div><div className="art-bottomline"><ChartNoAxesCombined size={21} /><div><strong>One vision. Every touchpoint.</strong><span>Strategy → Creative → Execution</span></div><ArrowUpRight size={20} /></div><p className="diagram-label">PLATFORM VISION · NOT LIVE PERFORMANCE DATA</p></div></section>
    <div className="stack-strip"><span>YOUR CONNECTED ADVANTAGE</span><b>Agency expertise</b><b>Brand intelligence</b><b>Digital experiences</b><b>Ava Skye AI</b></div>
    <section id="services" className="section"><div className="section-heading"><div><div className="eyebrow">MORE THAN A TOOLKIT</div><h2>Your ambition deserves<br />the whole picture.</h2></div><p className="muted">Software alone isn’t a growth strategy. Bring creative thinking, digital expertise, and a context-aware AI partner into the same conversation.</p></div><div className="service-grid">{services.map(({ icon: Icon, title, tag, text }) => <article className="service-card" key={tag}><div className="service-icon"><Icon size={23} /></div><span className="eyebrow">{tag}</span><h3>{title}</h3><p>{text}</p></article>)}</div><p className="fine">Agency capabilities and strategic service areas. The current self-service app includes Ava chat, private knowledge, and read-only X research; additional operational integrations are not yet implemented.</p></section>
    <section id="experience" className="section approach"><div className="eyebrow">CLARITY BEFORE COMPLEXITY</div><h2>Not more disconnected tools.<br /><span className="gradient-text">A better way forward.</span></h2><div className="cards">{[['01', 'Understand your business', 'Start with your audience, positioning, and goals. Build a foundation that sounds like you and solves the right problem.'], ['02', 'Connect the experience', 'Bring your brand, website, content, and campaign direction into one coherent customer journey.'], ['03', 'Make your next move', 'Use Ava to turn your private knowledge into practical strategy. Keep your team in control of publishing and execution.']].map(([n,t,d]) => <article key={n}><span>{n} / THE DIGIMARK APPROACH</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
    <section id="walkthrough" className="section walkthrough"><div><div className="eyebrow">MEET YOUR AI GROWTH PARTNER</div><h2>Ava Skye.<br />A sharper perspective.</h2><p className="muted">A private workspace for the thinking behind your next campaign. Your brand context. Your questions. A clearer next step.</p><ol><li>Sign in securely with your email.</li><li>Add your brand documents to your private knowledge base.</li><li>Ask Ava for strategy grounded in that context.</li><li>Explore recent X conversations to inform your plan.</li></ol><a className="secondary" href="#workspace">Open your command center <ArrowUpRight size={16} /></a></div><div className="video-panel">{safeVideo ? <video controls preload="metadata" aria-label="Ava Skye platform walkthrough"><source src={safeVideo} /><track kind="captions" src="/walkthrough.vtt" srcLang="en" label="English" />Your browser does not support video.</video> : <><div className="ava-monogram"><Sparkles size={32} /></div><span className="eyebrow">YOUR BRAND. YOUR INTELLIGENCE.</span><h3>Less blank page.<br />More breakthrough.</h3><p>Explore the actual workspace below.<br />No simulated conversations or invented results.</p><a className="secondary" href="#workspace">Start a conversation <ArrowUpRight size={16} /></a></>}</div></section>
    <Workspace />
    <section className="section offer"><div className="eyebrow">YOUR NEXT CHAPTER STARTS HERE</div><h2>Built for brands<br />that won’t stand still.</h2><p>Bring your ambition. Let’s give it direction.</p>{safeCheckout ? <a className="primary" href={safeCheckout} target="_blank" rel="noopener noreferrer">Continue with PayPal <ArrowUpRight size={17} /></a> : <a className="primary" href="#workspace">Explore with Ava <ArrowUpRight size={17} /></a>}{safeCheckout && <p className="fine">Payment does not automatically provision workspace access.</p>}</section>
    <footer><a className="logo" href="#top">DigiMark<span>101</span></a><p>Independent thinking. Connected growth.</p><small>© {new Date().getFullYear()} DigiMark101</small></footer>
  </main>
}
