import { Studio } from '@/components/platform/studio'
import { Workspace } from '@/components/platform/workspace'

export default function Home() {
  if (process.env.NEXT_PUBLIC_AVA_SITE === 'studio') return <Studio />
  const checkout = process.env.PAYPAL_CHECKOUT_URL
  const safeCheckout = checkout && /^https:\/\/(www\.)?(paypal\.com|paypal\.me)\//.test(checkout) ? checkout : null
  const video = process.env.AVA_WALKTHROUGH_VIDEO_URL
  const safeVideo = video?.startsWith('https://') ? video : null
  return <main id="top"><a className="skip-link" href="#workspace">Skip to workspace</a>
    <nav className="nav"><a href="#top" className="logo">DigiMark<span>101</span><small>THE AVA SKYE PLATFORM</small></a><div><a href="#experience">Experience</a><a href="#walkthrough">Walkthrough</a><a className="nav-cta" href="#workspace">Meet Ava ↗</a></div></nav>
    <section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="dot" /> YOUR AMBITION. A CLEARER DIRECTION.</div><h1>Your next chapter.<br />With <em>Ava Skye.</em></h1><p>Your AI growth partner for sharper strategy, stronger content, and a brand that moves forward. Built around your business—not another blank prompt.</p><div className="actions"><a className="primary" href="#workspace">Step inside with Ava ↗</a><a className="secondary" href="#walkthrough">Explore the platform ▶</a></div><div className="hero-meta">STRATEGY · KNOWLEDGE · SOCIAL INTELLIGENCE</div></div><div className="ava-art" aria-label="Abstract Ava Skye visual"><div className="orb" /><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="ava-wordmark">AVA<small>SKYE</small></div><div className="floating-note">A clearer path.<br /><strong>A smarter next move.</strong></div><span className="art-caption">HUMAN AMBITION. AI POSSIBILITY.</span></div></section>
    <div className="stack-strip"><span>BUILT FOR YOUR GROWTH</span><b>Brand strategy</b><b>Content direction</b><b>Private knowledge</b><b>Social research</b></div>
    <section id="experience" className="section"><div className="eyebrow">LESS FRICTION. MORE DIRECTION.</div><h2>One partner. Your whole growth picture.</h2><div className="cards">{[['01', 'Strategy with substance', 'Turn your goals into focused campaigns, clear positioning, and actionable next steps.'], ['02', 'Knowledge that stays yours', 'Give Ava your brand context. Supabase keeps the source of truth; Pinecone helps find what matters.'], ['03', 'A pulse on the conversation', 'Research recent conversations on X, then bring those insights into your next marketing decision.']].map(([n,t,d]) => <article key={n}><span>{n} / AVA SKYE</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
    <section id="walkthrough" className="section walkthrough"><div><div className="eyebrow">THE PLATFORM, AT A GLANCE</div><h2>From first hello<br />to your next big idea.</h2><p className="muted">A practical tour of your Ava workspace.</p><ol><li>Sign in securely with your email.</li><li>Add your brand knowledge to Supabase.</li><li>Ask Ava for strategy grounded in your documents.</li><li>Explore X research and refine your plan.</li></ol><a className="secondary" href="#workspace">Try the guided experience ↗</a></div><div className="video-panel">{safeVideo ? <video controls preload="metadata" aria-label="Ava Skye platform walkthrough"><source src={safeVideo} /><track kind="captions" src="/walkthrough.vtt" srcLang="en" label="English" />Your browser does not support video.</video> : <><span className="tour-mark" aria-hidden="true">01 → 02 → 03</span><h3>Your ambition. A practical plan.</h3><p>Start with your goals. Add your brand context.<br />Build your next move with Ava.</p><a className="secondary" href="#workspace">Open your workspace ↗</a></>}</div></section>
    <Workspace />
    <section className="section offer"><div className="eyebrow">BUILD YOUR NEXT CHAPTER</div><h2>Ready to grow with Ava?</h2><p>Bring your ideas. Find your focus. Make your next move.</p>{safeCheckout ? <a className="primary" href={safeCheckout} target="_blank" rel="noopener noreferrer">Continue with PayPal ↗</a> : <a className="primary" href="#workspace">Start with Ava ↗</a>}{safeCheckout && <p className="fine">Payment does not automatically provision workspace access.</p>}</section>
    <footer><a className="logo" href="#top">DigiMark<span>101</span></a><p>Built for human ambition. Guided by Ava Skye.</p><small>© {new Date().getFullYear()} DigiMark101</small></footer>
  </main>
}
