'use client'
import { useEffect, useState } from 'react'
import { supabase } from '@/lib/supabase-browser'
type Entry = {id:string;kind:string;title:string;content:string;created_at:string}
export function Workspace({kind}:{kind:string}){
 const [entries,setEntries]=useState<Entry[]>([]),[title,setTitle]=useState(''),[content,setContent]=useState(''),[status,setStatus]=useState('Checking account…'),[userId,setUserId]=useState<string|null>(null),[ready,setReady]=useState(false),[busy,setBusy]=useState(false)
 const storageKey=`digimark-workspace-${kind}`
 useEffect(()=>{let alive=true;let generation=0;async function load(){const current=++generation;setReady(false);setEntries([]);setUserId(null);try{const {data}=supabase?await supabase.auth.getUser():{data:{user:null}};if(!alive||current!==generation)return;setUserId(data.user?.id||null);if(data.user&&supabase){const result=await supabase.from('digimark_workspace').select('*').eq('user_id',data.user.id).eq('kind',kind).order('created_at',{ascending:false});if(!alive||current!==generation)return;if(result.error)throw result.error;setEntries(result.data||[]);setStatus('Private Supabase workspace connected.')}else{const local=localStorage.getItem(storageKey);setEntries(local?JSON.parse(local):[]);setStatus('Local preview: saved only in this browser. Sign in for Supabase storage.')}}catch{if(!alive||current!==generation)return;setStatus('Could not load workspace. Check Supabase configuration and migrations.')}finally{if(alive&&current===generation)setReady(true)}}load();const subscription=supabase?.auth.onAuthStateChange(()=>{generation++;setEntries([]);setUserId(null);setReady(false);setTimeout(()=>{if(alive)void load()},0)});return()=>{alive=false;subscription?.data.subscription.unsubscribe()}},[kind,storageKey])
 async function save(e:React.FormEvent){e.preventDefault();if(!ready||busy||!title.trim()||!content.trim())return;setBusy(true);const row:Entry={id:crypto.randomUUID(),kind,title:title.trim(),content:content.trim(),created_at:new Date().toISOString()};try{if(userId&&supabase){const {error}=await supabase.from('digimark_workspace').insert({...row,user_id:userId});if(error)throw error}else localStorage.setItem(storageKey,JSON.stringify([row,...entries]));setEntries([row,...entries]);setTitle('');setContent('');setStatus(userId?'Saved privately to Supabase.':'Saved in this browser only.')}catch{setStatus('Save failed. Your draft remains in the form.')}finally{setBusy(false)}}
 async function remove(id:string){if(!confirm('Delete this item?'))return;try{const next=entries.filter(r=>r.id!==id);if(userId&&supabase){const {error}=await supabase.from('digimark_workspace').delete().eq('id',id).eq('user_id',userId);if(error)throw error}else localStorage.setItem(storageKey,JSON.stringify(next));setEntries(next)}catch{setStatus('Delete failed. Item retained.')}}
 function download(){const blob=new Blob([JSON.stringify(entries,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`digimark-${kind}.json`;a.click();URL.revokeObjectURL(url)}
 return <><p className="status" role="status">{status}</p><div className="workspace"><form onSubmit={save}><h2>Create {kind.toLowerCase()}</h2><label htmlFor="entry-title">Title / name</label><input id="entry-title" required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)}/><label htmlFor="entry-content">Details, notes or draft</label><textarea id="entry-content" required maxLength={20000} value={content} onChange={e=>setContent(e.target.value)}/><div className="actions"><button className="button" disabled={!ready||busy}>{busy?'Saving…':'Save item'}</button></div></form><div><h2>Your {kind.toLowerCase()}</h2><button className="outline" disabled={!ready} onClick={download}>Export JSON ↓</button>{!entries.length&&<p>No items yet. Create your first one.</p>}{entries.map(row=><article className="item" key={row.id}><h3>{row.title}</h3><p>{row.content}</p><button className="outline" onClick={()=>remove(row.id)}>Delete</button></article>)}</div></div></>
}
